name: langsplat
channels:
  - pytorch
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - open-clip-torch
  - plyfile
  - python>=3.10
  - pip
  - pytorch=*=*cuda11.8*
  - torchaudio=*=*cu118*
  - torchvision=*=*cu118*
  - tqdm
  - tensorboard
  - pip:
    - submodules/segment-anything-langsplat
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
    - opencv-python